---
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Copy conf files
  template: src={{item}} dest=/etc/nginx/sites-available/{{item}}
  with_items:
    - isma
    - vestnik-ivgma
    - priem
    - moodle
    - irbis64
    - libisma
    - stat
- name: Create links
  file:
    src: /etc/nginx/sites-available/{{item}} 
    dest: /etc/nginx/sites-enabled/{{item}}
    state: link
  with_items:
    - isma
    - vestnik-ivgma
    - priem
    - sign
    - moodle
    - irbis64
    - libisma
  notify:
    - reload nginx
