---
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Copy conf files
  template: src={{item}} dest=/etc/nginx/sites-available/{{item}}
  with_items:
    - chat
    - datalens
    - dpo
    - glpi
    - irbis64
    - irbis64_ivgma
    - isma
    - ivgma
    - libisma
    - moodle
    - moodle_ivgma
    - priem
    - priem2022_ivgma
    - priem2023_ivgma
    - scos
    - sign
    - vestnik-ivgma
    - wekan
- name: Create links
  file:
    src: /etc/nginx/sites-available/{{item}} 
    dest: /etc/nginx/sites-enabled/{{item}}
    state: link
  with_items:
    - isma
    - vestnik-ivgma
    - priem
    - sign
    - moodle
    - irbis64
    - libisma
  notify:
    - reload nginx
