---
- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - curl
- name: Create moodledata
  file:
    path: /var/www/moodledata
    state: directory
    owner: www-data
    group: www-data
    mode: 0700
