---
- hosts: isma_gw 
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Install python
      raw: sudo apt install python-simplejson -y

  roles:
    - common
    - dhcp
    - dns
    - openvpn
    - shorewall
