---
- hosts: ivgmu_gw
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    ansible_user={{sudo_user}}
    ansible_sudo_pass={{sudo_password}}
  pre_tasks:
    - name: Install python
      raw: sudo apt install python-simplejson -y

  roles:
    - apt
    - shorewall
    - nginx
    - dns
    - dhcp
    - network
