---
- name: Install shorewall
  apt:
    name: shorewall
    state: present
- name: Configure shorewall
  template: 
    src: shorewall.conf
    dest: /etc/shorewall/shorewall.conf
- name: Configure shorewall zones
  template: 
    src: zones
    dest: /etc/shorewall/zones
- name: Configure shorewall interfaces
  template: 
    src: "{{shorewall_interfeces}}"
    dest: /etc/shorewall/interfaces
- name: Configure shorewall masq
  template: 
    src: "{{shorewall_masq}}"
    dest: /etc/shorewall/masq
- name: Configure shorewall policy
  template: 
    src: policy
    dest: /etc/shorewall/policy
- name: Configure shorewall rules
  template: 
    src: rules
    dest: /etc/shorewall/rules
- name: Configure shorewall stoppedrules
  template: 
    src: "{{shorewall_stoppedrules}}"
    dest: /etc/shorewall/stoppedrules
- name: Configure shorewall tcinterfaces
  template: 
    src: "{{shorewall_tcinterfaces}}"
    dest: /etc/shorewall/tcinterfaces
- name: Configure shorewall tcpri
  template: 
    src: tcpri
    dest: /etc/shorewall/tcpri
- name: Configure shorewall blrules
  template: 
    src: blrules
    dest: /etc/shorewall/blrules
  notify:
    - restart shorewall
