---
- name: Install dns
  apt:
    name: bind9
    state: present
- name: Configure bind9
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  notify:
    - restart dns
- name: Configure zone isma.ivanovo.ru
  template:
    src: db.isma.ivanovo.ru
    dest: /etc/bind/db.isma.ivanovo.ru
  notify:
    - restart dns
- name: Configure zone vestnik-ivgma
  template:
    src: db.vestnik-ivgma.ru
    dest: /etc/bind/db.vestnik-ivgma.ru
  notify:
    - restart dns
