network:
  ethernets:
    {{external_interface}}:
      dhcp4: false
      addresses:
        - {{external_subnet}}
      gateway4: {{external_gateway}}
      nameservers:
        addresses: [{{ya_ns1}}, {{ya_ns2}}]
    {{internal_interface}}:
      dhcp4: false
      addresses:
        - {{internal_address}}/24
      nameservers:
        addresses: [{{ya_ns1}}, {{ya_ns2}}]
      routes:
        - to: {{lxc_subnet2}}
          via: {{lxc_host2}}
        - to: {{lxc_subnet3}}
          via: {{lxc_host3}}
  version: 2
