network:
  ethernets:
    {{external_interface}}:
      dhcp4: false
      addresses:
        - {{external_subnet}}
      gateway4: {{external_gateway}}
      nameservers:
        addresses: [{{ya_ns1}}, {{ya_ns2}}]
    {{internal_interface}}:
      dhcp4: false
      addresses:
        - {{internal_address}}/24
      nameservers:
        addresses: [{{ya_ns1}}, {{ya_ns2}}]
      routes:
        - to: {{lxc_subnet01}}
          via: {{lxc01}}
        - to: {{lxc_subnet02}}
          via: {{lxc02}}
        - to:  172.16.15.0/26 
          via: {{vipnet_ip}}
  version: 2
