---
- name: Set authorized key took from file
  authorized_key:
    user: user
    state: present
    key: "{{ lookup('file', '/home/markovnin/.ssh/id_rsa.pub') }}"
- name: update & upgrade
  apt:
    update_cache: yes
    upgrade: full
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - mc
    - ntp
    - vim
    - wine
    - vlc
    - p7zip-full
    - p7zip-rar
    - libreoffice
    - dosbox
    - dosemu
    - firefox
    - ttf-mscorefonts-installer
- name: configure interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces
  notify:
    - restart networking
  
