---
- name: Ugrade
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
    update_cache: yes
- name: Install packages
  apt: 
    name: ['ntp', 'inetutils-traceroute', 'nmap', 'net-tools']
    state: present
