---
- name: Ugrade
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    autoclean: yes
- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - vim
    - ntp
