---
- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-php
- name: Configure apache2
  template:
    src: moodle.conf
    dest: /etc/apache2/sites-available/moodle.conf
- name: Enable moodle
  command: a2ensite moodle.conf
  notify:
    - restart apache2
