---
- name: Install openvpn
  apt: name={{item}} state=present
  with_items:
    - openvpn
- name: Copy keys files
  copy: src={{item}} dest=/etc/openvpn/{{item}}
  with_items:
    - ca.crt
    - ca.key
    - dh2048.pem
    - server.crt
    - server.key
    - ta.key
- name: Configure openvpn
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf
  notify:
    - restart openvpn
