- name: Install curl
  apt:
    name: curl
    state: present
- name: Install mc
  apt:
    name: mc
    state: present
- name: Install vim
  apt:
    name: vim
    state: present
- name: Install htop
  apt:
    name: htop
    state: present
- name: Install ntp
  apt:
    name: ntp
    state: present
- name: Configure interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces
  notify:
    - restart networking
