---
- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - mc
    - vim
    - htop
    - ntp
- name: Configure interfaces
  template:
    src: "{{common_interfaces}}"
    dest: /etc/network/interfaces
  notify:
    - restart networking
- name: Configure nameservers
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
  notify:
    - restart networking
