---
- name: Install aptitude
  apt: 
    name: aptitude
    state: present
    update_cache: yes
- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - mc
    - vim
    - htop
    - ntp
- name: Ugrade
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
- name: Configure interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces
  notify:
    - restart networking
