---
- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - mc
    - vim
    - htop
    - ntp
- name: Configure interfaces
  template:
    src: "{{interfaces}}"
    dest: /etc/network/interfaces
  notify:
    - restart networking
