---
- hosts: class
  remote_user: user
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Install python & aptitude
      raw: sudo apt install python-simplejson aptitude -y

  roles:
    - common
    - gsettings
    - wine
